name: Commit Build

on:
  push:
    branches: 
      - '**'
    tags-ignore:
      - '**'

jobs:
  buildLinux:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Get Commit Ref
        run: |
          COMMIT_REF=$(git rev-parse --short $GITHUB_SHA)
          echo "COMMIT_REF: $COMMIT_REF"
          echo "COMMIT_REF=$COMMIT_REF" >>$GITHUB_ENV
          
#          echo "COMMIT_REF=$(git rev-parse --short $GITHUB_SHA)" >>$GITHUB_ENV

      - name: Build
        run: |
          export TZ='America/Los_Angeles'
          sudo apt-get install libncurses-dev
          sudo apt-get install srecord
          # make dist
          rm -rf .git*

      - name: List Output
        run: |
          # cd Binary
          ls -l
          find -type f -exec md5sum '{}' \;

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
#          name: RomWBW-${{env.GITHUB_SHA_SHORT}}-Linux
          name: RomWBW-${{env.COMMIT_REF}}-Linux
          path: .

  buildMacOS:
    runs-on: macOS-latest

    steps:
      - name: Make Slugs
        uses: rlespinasse/github-slug-action@v4.4.1

      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Get Commit Ref
        run: |
          COMMIT_REF=$(git rev-parse --short $GITHUB_SHA)
          echo "COMMIT_REF: $COMMIT_REF"
          echo "COMMIT_REF=$COMMIT_REF" >>$GITHUB_ENV

#          echo "COMMIT_REF=$(git rev-parse --short $GITHUB_SHA)" >>$GITHUB_ENV
#          echo "COMMIT_REF: $COMMIT_REF"

      - name: Build
        run: |
          export TZ='America/Los_Angeles'
          brew install srecord
          # make dist
          rm -rf .git*

      - name: List Output
        run: |
          # cd Binary
          ls -l
          find . -type f -exec md5 -r -- '{}' +;

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: RomWBW-${{env.COMMIT_REF}}-MacOS
          path: .
