name: Commit Build

on:
  push:
    tags:
      - v*

jobs:
  buildLinux:

    runs-on: ubuntu-latest

    steps:
      - uses: rlespinasse/github-slug-action@v4.4.0

      - uses: actions/checkout@v3.3.0

      - name: Build
        run: |
          export TZ='America/Los_Angeles'
          # sudo apt-get install libncurses-dev
          # sudo apt-get install srecord
          # make dist
          rm -rf .git*

      - name: List Output
        run: |
          # cd Binary
          # ls -l
          # find -type f -exec md5sum '{}' \;

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: RomWBW_Linux-${{env.GITHUB_REF_SLUG}}-${{env.GITHUB_SHA_SHORT}}
          path: .

      - name: Create Package Archive
        run: |
            zip -r RomWBW-SnapShot-Package.zip .

#      - name: Post SnapShot
#        uses: docker://antonyurchenko/git-release:latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          RELEASE_NAME_PREFIX: "Development SnapShot Release "
#          CHANGELOG_FILE: "none"
#        with:
#          args: |
#            RomWBW-SnapShot-Package.zip
            
#      - name: Post SnapShot
#        uses: cb80/pubrel@latest
#        with:
#          replace: true
#          files: |
#            RomWBW-SnapShot-Package.zip

      - name: Post SnapShot
        uses: wwarthen/actions/packages/automatic-releases@built-packages
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "RomWBW Development SnapShot ${{env.GITHUB_REF_SLUG}}"
          files: |
            RomWBW-SnapShot-Package.zip

      - name: Remove Older Releases
        uses: sgpublic/delete-release-action@v1.0
        with:
          release-drop: true
          release-keep-count: 2
          release-drop-tag: false
          pre-release-drop: true
          pre-release-keep-count: 1
          pre-release-drop-tag: false
          draft-drop: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buildMacOS:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Build
        run: |
          export TZ='America/Los_Angeles'
          # brew install srecord
          # make dist
          rm -rf .git*

      - name: List Output
        run: |
          # cd Binary
          # ls -l
          # find . -type f -exec md5 -r -- '{}' +;

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: RomWBW_MacOS
          path: .