name: Commit Build

on:
  push:
    branches: 
      - dev
    tags-ignore:
      - '**'

jobs:
  buildLinux:

    runs-on: ubuntu-latest

    steps:
      - uses: rlespinasse/github-slug-action@v4.4.0

      - uses: actions/checkout@v3.3.0

      - name: Build
        run: |
          export TZ='America/Los_Angeles'
          # sudo apt-get install libncurses-dev
          # sudo apt-get install srecord
          # make dist
          rm -rf .git*

      - name: List Output
        run: |
          # cd Binary
          # ls -l
          # find -type f -exec md5sum '{}' \;

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: RomWBW-Linux
          path: .

#      - name: Create Package Archive
#        run: |
#            zip -r RomWBW-SnapShot-Package.zip .

#      - name: Post SnapShot
#        uses: docker://antonyurchenko/git-release:latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          RELEASE_NAME_PREFIX: "Development SnapShot Release "
#          CHANGELOG_FILE: "none"
#        with:
#          args: |
#            RomWBW-SnapShot-Package.zip
            
#      - name: Post SnapShot
#        uses: cb80/pubrel@latest
#        with:
#          replace: true
#          files: |
#            RomWBW-SnapShot-Package.zip

#      - name: Post SnapShot
#        uses: wwarthen/actions/packages/automatic-releases@built-packages
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          prerelease: true
#          title: "RomWBW Development SnapShot ${{env.GITHUB_REF_SLUG}}"
#          files: |
#            RomWBW-SnapShot-Package.zip

#      - name: Remove Older Releases
#        uses: wwarthen/delete-release-action@v1.2
#        with:
#          release-drop: true
#          release-keep-count: 0
#          release-drop-tag: true
#          pre-release-drop: false
#          pre-release-keep-count: 0
#          pre-release-drop-tag: true
#          draft-drop: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Remove Older Releases
#        uses: s00d/delete-older-releases@0.2.1
#        with:
#          keep_latest: 1
##          delete_tag_pattern: beta # defaults to ""
#          delete_type: 'release'
#          delete_branch: 'main'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buildMacOS:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Build
        run: |
          export TZ='America/Los_Angeles'
          # brew install srecord
          # make dist
          rm -rf .git*

      - name: List Output
        run: |
          # cd Binary
          # ls -l
          # find . -type f -exec md5 -r -- '{}' +;

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: RomWBW-MacOS
          path: .