name: Release Build

on:
  push:
    tags:
      - '**'

jobs:

  # Build new release
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"