name: Release Build

on:
  release:
    types: published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      
      - name: Create Package Label
        run: |
          LABEL=`echo "$GITHUB_REF" | sed "s|^refs/tags/||"`
          echo "PKGLBL=$LABEL" >> $GITHUB_ENV
         
      - name: Display Diagnostics
        run: |
          echo PKGLBL: "$PKGLBL"
          echo Upload URL: "${{github.event.release.upload_url}}"
          echo GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          
      - name: Build
        run: |
          # export TZ='America/Los_Angeles'
          # sudo apt-get install libncurses-dev
          # sudo apt-get install srecord
          # make dist
          rm -rf .git*
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: RomWBW-${{env.PKGLBL}}-Package
          path: .
      
      - name: Create Package Archive
        run: |
            zip -r Package.zip .
          
      - name: Upload Release Package
        uses: svenstaro/upload-release-action@2.5.0
        with:
          file: Package.zip
          asset_name: RomWBW-$tag-Package.zip
          overwrite: true
